// ============================================================
// SHADOW ECHO (シャドウエコー) - ゲーム設定定数
// ============================================================
const GameConfig = {
  WIDTH: 960,
  HEIGHT: 540,
  TILE_SIZE: 48,

  COLORS: {
    BG:          0x0d0d1a,
    FLOOR:       0x1c1c2e,
    FLOOR_ALT:   0x161626,
    WALL:        0x08080f,
    WALL_TOP:    0x12121e,
    GRASS:       0x0d1e0d,
    GRASS_DARK:  0x0a170a,
    WATER:       0x070c1e,
    STONE:       0x1a1814,
    SAND:        0x2a2416,
    PLAYER:      0xe8e0d0,
    PLAYER_DARK: 0xa89888,
    SHADE:       0x3d0050,
    SHADE_LIGHT: 0x5a1070,
    SHADE_EYE:   0xff1010,
    SHADE_EYE2:  0xff6030,
    BOSS:        0x4a0020,
    BOSS_LIGHT:  0x780030,
    NPC_SKIN:    0xd4a870,
    WEISS:       0xf0f0ff,
    YONAH:       0xffddaa,
    POPOLA:      0xcc9966,
    UI_BG:       0x080818,
    UI_BG2:      0x0d0d24,
    UI_BORDER:   0xb8860b,
    UI_BORDER2:  0xdaa520,
    UI_TEXT:     0xf0e6c8,
    UI_TEXT_DIM: 0x888070,
    UI_PANEL:    0x0a0a20,
    HP_BAR:      0xcc2200,
    HP_BAR_BG:   0x330800,
    MP_BAR:      0x0044cc,
    MP_BAR_BG:   0x001133,
    EXP_BAR:     0x00aa44,
    EXP_BAR_BG:  0x002210,
    GOLD:        0xffd700,
    DAMAGE_NUM:  0xff4444,
    HEAL_NUM:    0x44ff88,
    MAGIC_NUM:   0x8888ff,
    CRIT_NUM:    0xffff44,
    COMBO_NUM:   0xff8800,
    SHADOW:      0x000000,
    WHITE:       0xffffff,
  },

  PLAYER: {
    BASE_HP:         150,
    BASE_MP:         60,
    BASE_ATK:        20,
    BASE_DEF:        8,
    BASE_SPD:        170,
    ROLL_SPEED:      420,
    ROLL_DURATION:   280,
    ROLL_COOLDOWN:   750,
    ATTACK_COOLDOWN: 380,
    HEAVY_COOLDOWN:  700,
    MAGIC_COOLDOWN:  500,
    COMBO_WINDOW:    650,
    MAGIC_COST:      15,
    HEAVY_COST:      0,
    INV_FRAMES:      380,
    HIT_STUN:        250,
    INTERACT_RANGE:  80,
    ATTACK_RANGE:    60,
    HEAVY_RANGE:     80,
    ATTACK_DAMAGE_MULTIPLIERS: [1.0, 1.0, 1.5],
    HEAVY_DAMAGE_MULTIPLIER:   2.2,
    MAGIC_DAMAGE_MULTIPLIER:   1.8,
  },

  CAMERA: {
    LERP:      0.08,
    ZOOM:      1.0,
  },

  FONT: {
    PRIMARY:  { fontFamily: '"Palatino Linotype", Palatino, serif', fontSize: '16px',  color: '#f0e6c8' },
    LARGE:    { fontFamily: '"Palatino Linotype", Palatino, serif', fontSize: '24px',  color: '#f0e6c8' },
    XLARGE:   { fontFamily: '"Palatino Linotype", Palatino, serif', fontSize: '32px',  color: '#f0e6c8' },
    SMALL:    { fontFamily: '"Palatino Linotype", Palatino, serif', fontSize: '12px',  color: '#f0e6c8' },
    TINY:     { fontFamily: '"Palatino Linotype", Palatino, serif', fontSize: '10px',  color: '#888070' },
    TITLE:    { fontFamily: '"Palatino Linotype", Palatino, serif', fontSize: '56px',  color: '#daa520', stroke: '#000000', strokeThickness: 4 },
    SUBTITLE: { fontFamily: '"Palatino Linotype", Palatino, serif', fontSize: '18px',  color: '#c8b890' },
    DIALOG:   { fontFamily: '"Palatino Linotype", Palatino, serif', fontSize: '15px',  color: '#f0e6c8', wordWrap: { width: 680 }, lineSpacing: 6 },
    DIALOG_SPEAKER: { fontFamily: '"Palatino Linotype", Palatino, serif', fontSize: '17px', color: '#daa520', fontStyle: 'bold' },
    DAMAGE:   { fontFamily: 'Arial, sans-serif', fontSize: '22px',  color: '#ff4444',  stroke: '#000000', strokeThickness: 3 },
    HEAL:     { fontFamily: 'Arial, sans-serif', fontSize: '22px',  color: '#44ff88',  stroke: '#000000', strokeThickness: 3 },
    MAGIC:    { fontFamily: 'Arial, sans-serif', fontSize: '22px',  color: '#8888ff',  stroke: '#000000', strokeThickness: 3 },
    CRIT:     { fontFamily: 'Arial, sans-serif', fontSize: '28px',  color: '#ffff44',  stroke: '#000000', strokeThickness: 4 },
    GOLD:     { fontFamily: '"Palatino Linotype", Palatino, serif', fontSize: '14px',  color: '#ffd700' },
    LEVEL:    { fontFamily: '"Palatino Linotype", Palatino, serif', fontSize: '14px',  color: '#daa520', fontStyle: 'bold' },
    HINT:     { fontFamily: '"Palatino Linotype", Palatino, serif', fontSize: '13px',  color: '#888888', fontStyle: 'italic' },
    MENU:     { fontFamily: '"Palatino Linotype", Palatino, serif', fontSize: '20px',  color: '#f0e6c8' },
    MENU_SEL: { fontFamily: '"Palatino Linotype", Palatino, serif', fontSize: '20px',  color: '#daa520', fontStyle: 'bold' },
    AREA:     { fontFamily: '"Palatino Linotype", Palatino, serif', fontSize: '22px',  color: '#c8b890', stroke: '#000000', strokeThickness: 3 },
  },

  DEPTH: {
    GROUND:     0,
    SHADOWS:    1,
    OBJECTS:    5,
    PLAYER:     10,
    ENEMIES:    8,
    NPCS:       9,
    PROJECTILES:12,
    EFFECTS:    15,
    UI:         20,
    OVERLAY:    30,
    DIALOG:     40,
    TRANSITION: 50,
  },

  LEVEL: {
    MAX: 20,
    EXP_BASE: 100,
    EXP_FACTOR: 1.5,
    HP_PER_LEVEL:  20,
    MP_PER_LEVEL:   8,
    ATK_PER_LEVEL:  3,
    DEF_PER_LEVEL:  2,
  },
};
